[build]
  base = "."
  publish = "build"
  command = "CI=false npm install --legacy-peer-deps && npx update-browserslist-db@latest && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200